version: "3.7"
services:
    app:
        build:
            args:
                user: xplore
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: presience-backend
        container_name: presience-backend-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - presience-backend

    db:
        image: mysql:latest
        container_name: presience-backend-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - presience-backend

    nginx:
        image: nginx:alpine
        container_name: presience-backend-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - presience-backend

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: presience-backend-phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80 # phpMyAdmin accessible on port 8080
        environment:
            PMA_HOST: presience-backend-db # The database service name
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Password for the root user
        networks:
            - presience-backend

networks:
    presience-backend:
        driver: bridge
